theme: jekyll-theme-architect
<!DOCTYPE html>
<html>
<head>
	<title>FabLab Heritage Nepal</title>
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="style.css">
</head>


<body>

	<div id="fond">

	<header>
		<h1>FabLab Heritage Nepal</h1>
		<h2>Save nepalese heritage tomorrow</h2>
	</header>
		
	<nav>
		<ul>
			<li><a href="....">Homepage</a></li>
			<li><a href="....">Community</a></li>
			<li><a href="....">Media library</a></li>
			<li><a href="....">My account</a></li>
		</ul>
	</nav>

	<div class="Gallery">
	</div>

	<section>
		<h3>What's the Fablab Heritage Nepal ?</h3>

		<p>FabLab Heritage Nepal, is a project for the preservation of Nepalese heritage.<br>

		This programme is about issues of architecture and handicrafts in the Kathmandu Valley supported by the new technologies offered by a FabLab. FabLab Heritage Nepal is composed of two mobile FabLabs, one on terracotta handicrafts, and a multi-disciplinary one on wood and metal crafts and new technology.<br>

		FabLab, on this website, which allows you to access all informations on the subject, to file your own contents and share them. Finally to keep in touch with the different actors of the FabLab.
		</p>	
	</section>

	<aside>
		Informations
	</aside>

	<FOOTER>


		<p>This project and this website are a work of Master in Architecture of ULB university.<br>
		By Lucie PARIYAR. @copyright 2020
	</footer>

</body>
</html>
